isTest: false
isPhidgetWebServer: false
phidgetWebServerIp: "10.3.8.200"
phidgetWebServerPort: 5001
analog:
  - "floor_sensors"
digital:
  - "doors_sensors"
identifiers:
  - 116542
  - 116543
development:
-
  position_number: 10
  sensors:
    analog:
      -
        type: "floor_sensors"
        identifier: 116542
        positions:
          - 0
    digital:
      -
        type: "doors_sensors"
        identifier: 116542
        positions:
          - 4
  indicators:
    -
      type: "led"
      identifier: 116542
      positions:
        - 3
  doors:
    back:
      -
        type: "dc_motorized"
        identifier: 116542
        positions:
          - 4
    front:
      -
        type: "garage"
        identifier: 116542
        positions:
          - 0
          - 1
-
  position_number: 10
  sensors:
    analog:
      -
        type: "floor_sensors"
        identifier: 116542
        positions:
          - 1
    digital:
      -
        type: "doors_sensors"
        identifier: 116542
        positions:
          - 5
  indicators:
    -
      type: "led"
      identifier: 116542
      positions:
        - 2
  doors:
    back:
      -
        type: "dc_motorized"
        identifier: 116542
        positions:
          - 4
    front:
      -
        type: "garage"
        identifier: 116542
        positions:
          - 0
          - 1
-
  position_number: 10
  sensors:
    analog:
      -
        type: "floor_sensors"
        identifier: 116542
        positions:
          - 2
    digital:
      -
        type: "doors_sensors"
        identifier: 116542
        positions:
          - 6
  indicators:
    -
      type: "led"
      identifier: 116542
      positions:
        - 1
  doors:
    back:
      -
        type: "dc_motorized"
        identifier: 116542
        positions:
          - 4
    front:
      -
        type: "garage"
        identifier: 116542
        positions:
          - 0
          - 1
-
  position_number: 10
  sensors:
    analog:
      -
        type: "floor_sensors"
        identifier: 116542
        positions:
          - 3
    digital:
      -
        type: "doors_sensors"
        identifier: 116542
        positions:
          - 7
  indicators:
    -
      type: "led"
      identifier: 116542
      positions:
        - 0
  doors:
    back:
      -
        type: "dc_motorized"
        identifier: 116542
        positions:
          - 4
    front:
      -
        type: "garage"
        identifier: 116542
        positions:
          - 0
          - 1

